---
# Page meta info, like heading, footer text and nav links
pageInfo:
  title: Dashy
  description: Welcome to your new dashboard!
  navLinks:
    - title: GitHub
      path: https://github.com/Lissy93/dashy
    - title: Documentation
      path: https://dashy.to/docs

# Optional app settings and configuration
appConfig:
  theme: colorful

# Main content - An array of sections, each containing an array of items
sections:
  - name: Getting Started
    icon: fas fa-rocket
    items:
      - title: Dashy Live
        description: Development a project management links for Dashy
        icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
        url: https://live.dashy.to/
        target: newtab
      - title: GitHub
        description: Source Code, Issues and Pull Requests
        url: https://github.com/lissy93/dashy
        icon: favicon
      - title: Docs
        description: Configuring & Usage Documentation
        provider: Dashy.to
        icon: far fa-book
        url: https://dashy.to/docs
      - title: Showcase
        description: See how others are using Dashy
        url: https://github.com/Lissy93/dashy/blob/master/docs/showcase.md
        icon: far fa-grin-hearts
      - title: Config Guide
        description: See full list of configuration options
        url: https://github.com/Lissy93/dashy/blob/master/docs/configuring.md
        icon: fas fa-wrench
      - title: Support
        description: Get help with Dashy, raise a bug, or get in contact
        url: https://github.com/Lissy93/dashy/blob/master/.github/SUPPORT.md
        icon: far fa-hands-helping

  - name: Network Tools
    icon: https://cdn-icons-png.flaticon.com/512/2092/2092294.png
    items:
      - title: Pi-hole
        icon: https://upload.wikimedia.org/wikipedia/commons/0/00/Pi-hole_Logo.png
        url: http://192.168.68.35:8081/admin/
        description: "Network-wide ad blocker UI"
      - title: Glances
        icon: https://media.sys.truenas.net/apps/glances/icons/icon.png
        url: http://192.168.68.35:61208
        description: "System monitoring tool"
      - title: Home Assistant
        icon: https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/New_Home_Assistant_logo.svg/2048px-New_Home_Assistant_logo.svg.png
        url: http://192.168.68.35:8123
        description: "Home automation platform UI"
      - title: n8n
        icon: https://n8n.io/favicon.ico
        url: http://192.168.68.35:5678
        description: "Workflow automation tool"
